### ISSUE TITLE
map in tol barad

### ISSUE THREAD

**Issue by Dean1989** [Apollyonn/ElvUI-4.3.4#10]
i always notice this bug in tol barad, some of the ppl icon on the map have like corrupted textures.
![ss 2016-07-19 at 07 57 41](https://cloud.githubusercontent.com/assets/8077498/16961666/c487b02a-4dee-11e6-9738-982b5f5df0d9.jpg)

**Comment by smmuntz** [comment]
I am not sure that this is actually due to ElvUI but something in the game itself, as I see this sometimes on the map, and I don't even have ElvUI yet (just decided to check out this bugracker while checking it out).

**Comment by Apollyonn** [comment]
Not an Elvui problem, server-side or maybe blizzard bug, happens with normal map too.
