### ISSUE TITLE
world map

### ISSUE THREAD

**Issue by Docholiday-Atlantiss** [Apollyonn/ElvUI-4.3.4#12]
the issue i have now with the world map unless it has been fixed in a recent update. When I log in i opne the map and it is a small version. I click to make it a full map and it will stay like that opening and closing the map aslong as I am online. Once I log out then log back in the map returns to the small version. Like it is not saving it to say hey he was last seen with a large map.

**Comment by Apollyonn** [comment]
![wowscrnshot_081616_010349](https://cloud.githubusercontent.com/assets/19589902/17681293/89d30b2c-634d-11e6-9328-fef54989baa6.jpg)
Uncheck this

**Comment by Docholiday-Atlantiss** [comment]
Thanks dont think that should be checked by default never had to mess with that
