### ISSUE TITLE
Unit Frame Buffs

### ISSUE THREAD

**Issue by Docholiday-Atlantiss** [Apollyonn/ElvUI-4.3.4#4]
The unit frame buff show through the wow map.
Both player and target buff along with resource number.

![wowscrnshot_061816_141053](https://cloud.githubusercontent.com/assets/12252441/16172827/95a1490e-355e-11e6-86b0-6039e0cd8186.jpg)

**Comment by Apollyonn** [comment]
When the map is skinned there is no problem with it,
![wowscrnshot_061816_221410](https://cloud.githubusercontent.com/assets/19589902/16173202/a786c114-35a2-11e6-9070-33e7af0c8564.jpg)
Did you disable it on purpose cause you don't like it or it was disabled by default?
I'm gonna have a look and try to fix it anyways :)

**Comment by Thefakemccoy** [comment]
I disable it as i like some default parts of wow interface.

**Comment by Apollyonn** [comment]
can't fix it without breaking other stuff

**Comment by Apollyonn** [comment]
fixed
