### ISSUE TITLE
apollyonn check this

### ISSUE THREAD

**Issue by Dean1989** [Apollyonn/ElvUI-4.3.4#6]
hello apo check the link i've posted on the forum, maybe it can help you http://community.atlantiss.eu/index.php?/topic/10305-elvui-backported-version/?p=50912

**Comment by Apollyonn** [comment]
I have fixed the unitframes, its will not be 100% ready but its going to be functional. will upload later

**Comment by Dean1989** [comment]
nice, i'm trying it. few things i noticed:
1) can't right click on the party frames for inspect/kick for example
2) heal prediction don't work
3)roles icons are under the names and barely visible
4)the % number displayed when you lose hp is very close to the name 
[img]http://puu.sh/q0FVO/fe4b2ec84a.jpg[/ing]

**Comment by Apollyonn** [comment]
1) I have removed Heal Prediction cause it was for the 3.3.5 client, i will add it later.
2) I'm trying to figure out why right click doesn't work, it might be something very simple that i'm missing, for now you can just select the person from the party/raid frame and then right click the target frame.

Here are some screenshot that will help you with the settings.
![wowscrnshot_071416_014539](https://cloud.githubusercontent.com/assets/19589902/16822499/971a77d6-4965-11e6-8371-6430d0d62b2e.jpg)
![wowscrnshot_071416_014543](https://cloud.githubusercontent.com/assets/19589902/16822501/9c1cf204-4965-11e6-8e76-e555b138c90f.jpg)

**Comment by Dean1989** [comment]
ty for the screens i solved my problems related to font/icons
