### ISSUE TITLE
battle shout/elixir minimap icon

### ISSUE THREAD

**Issue by Dean1989** [Apollyonn/ElvUI-4.3.4#7]
hello, battle shout/horn of winter/roar of courage (hunter's cat pet buff)/strength of earth totem icon on the minimap don't display the buff time, the elixir icon have the same problem. as always ty for your work we love it <3
![buffs](https://cloud.githubusercontent.com/assets/8077498/16904931/bef680f6-4c9e-11e6-84cf-b66af105683a.jpg)

**Comment by Apollyonn** [comment]
whats the name of the elixir? is it a cataclysm one?

**Comment by Dean1989** [comment]
no i've just tried with an onslaught elixir http://www.wowhead.com/item=28102/onslaught-elixir
if the icon is by id and show only cata elixir there is no problem

**Comment by Apollyonn** [comment]
Battleshout works after the update?

**Comment by Dean1989** [comment]
yes horn, pet buff, totem too
