### ISSUE TITLE
issue with party frame when kick/leave ppl

### ISSUE THREAD

**Issue by Dean1989** [Apollyonn/ElvUI-4.3.4#8]
after a player get kicked or leave from the rdf party, some party frames members names and colors are messed up.
for ex in these ss we kicked the dk tank and you can see the hunter got the dk name in red color and the druid the hunter name in green. targeting the ppl show their correct name/color class.
![wowscrnshot_071916_190226](https://cloud.githubusercontent.com/assets/8077498/16961247/efb02cde-4dec-11e6-856a-ca018b2210f0.jpg)
![wowscrnshot_071916_190229](https://cloud.githubusercontent.com/assets/8077498/16961252/f3626662-4dec-11e6-8134-dbc71abbb3e7.jpg)

**Comment by Apollyonn** [comment]
I think this is a server side issue, if all players are inside the dungeon/bg/raid there is no such problem, i think the problem is with the server phasing, I'm not 100 sure about that tho...i have to test it on other servers than Atlantiss.

**Comment by Apollyonn** [comment]
fixed
