### ISSUE TITLE
(suggestion) role icons in rdf

### ISSUE THREAD

**Issue by Dean1989** [Apollyonn/ElvUI-4.3.4#9]
i like the skinned role icons but i find it a bit pixelated, is possibile have a better resolution of the icons?
and if you like i think the wod elvui icons are nice too.
![ss 2016-07-19 at 07 41 55](https://cloud.githubusercontent.com/assets/8077498/16961536/3a2660d4-4dee-11e6-8602-f65becc8395e.jpg)

**Comment by Apollyonn** [comment]
Ye i took them from Aurora Ui and i still haven't finish it. They are not so nice but they are better than the default blizzard icons. Ye its possible to add these but i don't know how they are going to look to other frames like Rolecheck or the dungeon wait status.

**Comment by Apollyonn** [comment]
Does this looks better?
![wowscrnshot_072016_145312](https://cloud.githubusercontent.com/assets/19589902/16985604/426eba6a-4e8a-11e6-8ced-9f36600a241b.jpg)
![wowscrnshot_072016_145434](https://cloud.githubusercontent.com/assets/19589902/16985608/461285f2-4e8a-11e6-949d-c816bec00427.jpg)
![wowscrnshot_072016_145553](https://cloud.githubusercontent.com/assets/19589902/16985609/4903751e-4e8a-11e6-870c-47302440a4c8.jpg)

**Comment by Dean1989** [comment]
yes these are very beautiful gj!
i want to add a little thing without open a new topic, in the datatexts panel there is a statistics called speed, i think is better rename it haste since can be a wrong translation from bunny since he's russian.

**Comment by Apollyonn** [comment]
Speed is correct, the datatext name takes info from the speed stat of your characters panel but the tooltip shows the haste rating and the speed. The name is a little confusing. When i first saw this datatext i thought it was the moving speed of my char. I'm just gonna change it to haste then.

**Comment by Dean1989** [comment]
indeed was the same thing I thought the first time lol
